# Main things like includes, font and other
[main]
font               = SF Mono:size=18
use-bold           = yes
dpi-aware          = no
terminal           = foot -e --app-id=yazifilechooser
placeholder        = "Enter text..."
prompt             = "🔍︎ "
icons-enabled      = no
hide-before-typing = yes
anchor             = top
y-margin           = 140
lines              = 5
minimal-lines      = yes
width              = 34
horizontal-pad     = 10
vertical-pad       = 10
inner-pad          = 5

#[colors]
#border = 00ffffff

[colors]
background=1e1e2edd
text=cdd6f4ff
prompt=bac2deff
placeholder=7f849cff
input=cdd6f4ff
match=b4befeff
selection=585b70ff
selection-text=cdd6f4ff
selection-match=b4befeff
counter=7f849cff
border=b4befeff

# Border stuff
[border]
width  = 4
radius = 12

# Vim mode binds
[key-bindings]
cursor-left-word  = Mod1+h
next              = Mod1+j
prev              = Mod1+k
cursor-right-word = Mod1+l
