#     __________  ____  ______
#    / ____/ __ \/ __ \/_  __/
#   / /_  / / / / / / / / /   
#  / __/ / /_/ / /_/ / / /    
# /_/    \____/\____/ /_/     

# Fonts and other same stuff
[main]
include             = ~/.config/foot/themes/mocha
term                = xterm-256color
font                = SF Mono:size=11
font-bold           = SF Mono:weight=heavy:size=11
font-italic         = SF Mono:slant=italic:size=11
font-bold-italic    = SF Mono:weight=heavy:size=11:slant=italic
#font-italic         = Cartograph CF:slant=italic:size=11
#font-bold-italic    = Cartograph CF:slant=italic:weight=heavy:size=11
pad     = 5x10
app-id  = foot
#dpi-aware=yes

[colors]
#alpha = 0.85
#alpha = 0.99

[scrollback]
lines = 5000

# Underline cursor
[cursor]
#style           = underline
style           = block
unfocused-style = hollow
#blink           = yes
#blink-rate      = 666

# Very useful setting
[mouse]
hide-when-typing = yes
